import { Skill, SkillDefinition } from "@localtypes/types";

const skillDefinitions: Record<Skill, SkillDefinition> = {
  "1B's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "1B's Resolve",
    valuesByPosition: {
      "0": 2.3,
      "1B": 2.3,
    },
  },
  "2B's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "2B's Resolve",
    valuesByPosition: {
      "0": 2.5,
      "2B": 2.5,
    },
  },
  "3B's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "3B's Resolve",
    valuesByPosition: {
      "0": 2.3,
      "3B": 2.3,
    },
  },
  "C's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "C's Resolve",
    valuesByPosition: {
      "0": 2.8,
      C: 2.8,
    },
  },
  "CF's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "CF's Resolve",
    valuesByPosition: {
      "0": 2.5,
      CF: 2.5,
    },
  },
  "HR King Blessing": {
    skillGrade: "UR",
    type: "Common",
    name: "HR King Blessing",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Idol's Swing": {
    name: "Idol's Swing",
    type: "Batting Style",
    skillGrade: "UR",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "LF's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "LF's Resolve",
    valuesByPosition: {
      "0": 2.3,
      LF: 2.3,
    },
  },
  "RF's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "RF's Resolve",
    valuesByPosition: {
      "0": 2.3,
      RF: 2.3,
    },
  },
  "SS's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "SS's Resolve",
    valuesByPosition: {
      "0": 2.5,
      SS: 2.5,
    },
  },
  "Switch Hitter": {
    skillGrade: "UR",
    type: "Common",
    name: "Switch Hitter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Top Batter Blessing": {
    skillGrade: "UR",
    type: "Common",
    name: "Top Batter Blessing",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Big Bang": {
    skillGrade: "SSR",
    type: "Batting Style",
    name: "Big Bang",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Framing: {
    skillGrade: "SSR",
    type: "Common",
    name: "Framing",
    valuesByPosition: {
      "0": 1,
      C: 1.5,
    },
  },
  "Full Swing": {
    skillGrade: "SSR",
    type: "Batting Style",
    name: "Full Swing",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Golden Arm": {
    skillGrade: "SSR",
    type: "Common",
    name: "Golden Arm",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.2,
      C: 1.05,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Hit Master": {
    skillGrade: "SSR",
    type: "Common",
    name: "Hit Master",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Home Run Master": {
    skillGrade: "SSR",
    type: "Common",
    name: "Home Run Master",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Horizontal Cut": {
    skillGrade: "SSR",
    type: "Batting Style",
    name: "Horizontal Cut",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Knuckleball Hunter": {
    skillGrade: "SSR",
    type: "Common",
    name: "Knuckleball Hunter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Power Batter": {
    skillGrade: "SSR",
    type: "Common",
    name: "Power Batter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Provoke: {
    skillGrade: "SSR",
    type: "Common",
    name: "Provoke",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Roadrunner: {
    skillGrade: "SSR",
    type: "Common",
    name: "Roadrunner",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Tenacity: {
    skillGrade: "SSR",
    type: "Common",
    name: "Tenacity",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Tight Defense": {
    skillGrade: "SSR",
    type: "Common",
    name: "Tight Defense",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1.05,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Anti LH Pitcher": {
    skillGrade: "SR",
    type: "Common",
    name: "Anti LH Pitcher",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Anti RH Pitcher": {
    skillGrade: "SR",
    type: "Common",
    name: "Anti RH Pitcher",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Burst: {
    skillGrade: "SR",
    type: "Batting Style",
    name: "Burst",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Dash: {
    skillGrade: "SR",
    type: "Common",
    name: "Dash",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1.05,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Drive: {
    skillGrade: "SR",
    type: "Batting Style",
    name: "Drive",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "High-Ball Batter": {
    skillGrade: "SR",
    type: "Batter Skills",
    name: "High-Ball Batter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "IF Catch God": {
    skillGrade: "SR",
    type: "Common",
    name: "IF Catch God",
    valuesByPosition: {
      "0": 1,
      "1B": 1.2,
      "2B": 1.2,
      "3B": 1.2,

      SS: 1.2,
    },
  },
  "IF Defense God": {
    skillGrade: "SR",
    type: "Common",
    name: "IF Defense God",
    valuesByPosition: {
      "0": 1,
      "1B": 1.2,
      "2B": 1.2,
      "3B": 1.2,

      SS: 1.2,
    },
  },
  "IF Throw God": {
    skillGrade: "SR",
    type: "Common",
    name: "IF Throw God",
    valuesByPosition: {
      "0": 1,
      "1B": 1.2,
      "2B": 1.2,
      "3B": 1.2,

      SS: 1.2,
    },
  },
  "Iron Wall": {
    skillGrade: "SR",
    type: "Common",
    name: "Iron Wall",
    valuesByPosition: {
      "0": 1,

      C: 1.5,
    },
  },
  "Low-Ball Batter": {
    skillGrade: "SR",
    type: "Batter Skills",
    name: "Low-Ball Batter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "OF Catch God": {
    skillGrade: "SR",
    type: "Common",
    name: "OF Catch God",
    valuesByPosition: {
      "0": 1,

      CF: 1.2,
      LF: 1.2,
      RF: 1.2,
    },
  },
  "OF Defense God": {
    skillGrade: "SR",
    type: "Common",
    name: "OF Defense God",
    valuesByPosition: {
      "0": 1,

      CF: 1.2,
      LF: 1.2,
      RF: 1.2,
    },
  },
  "OF Throw God": {
    skillGrade: "SR",
    type: "Common",
    name: "OF Throw God",
    valuesByPosition: {
      "0": 1,

      CF: 1.2,
      LF: 1.2,
      RF: 1.2,
    },
  },
  "Pull-Hit": {
    skillGrade: "SR",
    type: "Batter Skills",
    name: "Pull-Hit",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Push-hit": {
    skillGrade: "SR",
    type: "Batter Skills",
    name: "Push-hit",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Super Jump": {
    skillGrade: "SR",
    type: "Common",
    name: "Super Jump",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1.05,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Super Slide": {
    skillGrade: "SR",
    type: "Common",
    name: "Super Slide",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1.05,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Target Sighted": {
    skillGrade: "SR",
    type: "Common",
    name: "Target Sighted",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Twister: {
    skillGrade: "SR",
    type: "Batting Style",
    name: "Twister",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Walk Machine": {
    skillGrade: "SR",
    type: "Common",
    name: "Walk Machine",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Early Challenge": {
    skillGrade: "R",
    type: "Common",
    name: "Early Challenge",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Error Prevention": {
    skillGrade: "R",
    type: "Common",
    name: "Error Prevention",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1.05,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Four-Seam Hunter": {
    skillGrade: "R",
    type: "Common",
    name: "Four-Seam Hunter",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Gambler: {
    skillGrade: "R",
    type: "Common",
    name: "Gambler",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Hustle: {
    skillGrade: "R",
    type: "Common",
    name: "Hustle",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1.05,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "New Resolution": {
    skillGrade: "R",
    type: "Common",
    name: "New Resolution",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Point Man": {
    skillGrade: "R",
    type: "Common",
    name: "Point Man",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Power Swing": {
    skillGrade: "R",
    type: "Batting Style",
    name: "Power Swing",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Pure Survival": {
    skillGrade: "R",
    type: "Common",
    name: "Pure Survival",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Scoring Chance": {
    skillGrade: "R",
    type: "Common",
    name: "Scoring Chance",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Short Swing": {
    skillGrade: "R",
    type: "Batting Style",
    name: "Short Swing",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Slugger Power": {
    skillGrade: "R",
    type: "Common",
    name: "Slugger Power",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Tactical Bunt": {
    skillGrade: "R",
    type: "Common",
    name: "Tactical Bunt",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  Chaser: {
    skillGrade: "N",
    type: "Common",
    name: "Chaser",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Dbl Play Machine": {
    skillGrade: "N",
    type: "Common",
    name: "Dbl Play Machine",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Focused Defense": {
    skillGrade: "N",
    type: "Common",
    name: "Focused Defense",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Human Magnet": {
    skillGrade: "N",
    type: "Common",
    name: "Human Magnet",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "No Stolen Bases": {
    skillGrade: "N",
    type: "Common",
    name: "No Stolen Bases",
    valuesByPosition: {
      "0": 1,

      C: 1.5,
    },
  },
  Terminator: {
    skillGrade: "N",
    type: "Common",
    name: "Terminator",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1.05,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "Walk-Off Hit": {
    skillGrade: "N",
    type: "Common",
    name: "Walk-Off Hit",
    valuesByPosition: {
      "0": 1,
      "1B": 1,
      "2B": 1,
      "3B": 1,
      C: 1,
      CF: 1,
      LF: 1,
      RF: 1,
      SS: 1,
    },
  },
  "CP's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "CP's Resolve",
    valuesByPosition: { "0": 2.1, CP: 2.1 },
  },
  Knuckleball: {
    skillGrade: "UR",
    type: "Pitch Type V",
    name: "Knuckleball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "MRP's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "MRP's Resolve",
    valuesByPosition: { "0": 1.6, CP: 0, RP: 1.6 },
  },
  "Perfect Pitch": {
    skillGrade: "UR",
    type: "Common",
    name: "Perfect Pitch",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "SP's Resolve": {
    skillGrade: "UR",
    type: "Resolve",
    name: "SP's Resolve",
    valuesByPosition: { "0": 1.6, CP: 0, SP: 1.6 },
  },
  "Super Left Arm": {
    skillGrade: "UR",
    type: "Hand",
    name: "Super Left Arm",
    valuesByPosition: {
      "0": 1.6,
      CP: 1.6,
      RP: 1.6,
      SP: 1.6,
    },
  },
  "Super Right Arm": {
    skillGrade: "UR",
    type: "Hand",
    name: "Super Right Arm",
    valuesByPosition: {
      "0": 1.6,
      CP: 1.6,
      RP: 1.6,
      SP: 1.6,
    },
  },
  "Supersonic Pitch": {
    skillGrade: "UR",
    type: "Common",
    name: "Supersonic Pitch",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Accuracy Control": {
    skillGrade: "SSR",
    type: "Common",
    name: "Accuracy Control",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Circle Changeup": {
    skillGrade: "SSR",
    type: "Pitch Type V",
    name: "Circle Changeup",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Double Step": {
    skillGrade: "SSR",
    type: "Pitching Style",
    name: "Double Step",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Heavy Ball": {
    skillGrade: "SSR",
    type: "Common",
    name: "Heavy Ball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Hit Blockade": {
    skillGrade: "SSR",
    type: "Common",
    name: "Hit Blockade",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Knuckle Curve": {
    skillGrade: "SSR",
    type: "Pitch Type III",
    name: "Knuckle Curve",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Man of Steel": {
    skillGrade: "SSR",
    type: "Common",
    name: "Man of Steel",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Maximum Effort": {
    skillGrade: "SSR",
    type: "Common",
    name: "Maximum Effort",
    valuesByPosition: { "0": 1, CP: 1.25, RP: 1, SP: 1 },
  },
  "Monstrous Pitch": {
    skillGrade: "SSR",
    type: "Common",
    name: "Monstrous Pitch",
    valuesByPosition: { "0": 1, CP: 1, RP: 1.25, SP: 1 },
  },
  Screwball: {
    skillGrade: "SSR",
    type: "Pitch Type VI",
    name: "Screwball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Shadow Trap": {
    skillGrade: "SSR",
    type: "Common",
    name: "Shadow Trap",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Slurve: {
    skillGrade: "SSR",
    type: "Pitch Type II",
    name: "Slurve",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Speed Control": {
    skillGrade: "SSR",
    type: "Common",
    name: "Speed Control",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1.25 },
  },
  Submarine: {
    skillGrade: "SSR",
    type: "Pitching Style",
    name: "Submarine",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Super Fastball": {
    skillGrade: "SSR",
    type: "Common",
    name: "Super Fastball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Tornado: {
    skillGrade: "SSR",
    type: "Pitching Style",
    name: "Tornado",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "V-Slider": {
    skillGrade: "SSR",
    type: "Pitch Type IV",
    name: "V-Slider",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Anti LH Batter": {
    skillGrade: "SR",
    type: "Common",
    name: "Anti LH Batter",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Anti RH Batter": {
    skillGrade: "SR",
    type: "Common",
    name: "Anti RH Batter",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Bold: {
    skillGrade: "SR",
    type: "Common",
    name: "Bold",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Changeup: {
    skillGrade: "SR",
    type: "Pitch Type V",
    name: "Changeup",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Curve: {
    skillGrade: "SR",
    type: "Pitch Type III",
    name: "Curve",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Cutter: {
    skillGrade: "SR",
    type: "Pitch Type II",
    name: "Cutter",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Forkball: {
    skillGrade: "SR",
    type: "Pitch Type IV",
    name: "Forkball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Four-Seam": {
    skillGrade: "SR",
    type: "Pitch Type I",
    name: "Four-Seam",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "High Kick": {
    skillGrade: "SR",
    type: "Pitching Style",
    name: "High Kick",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Mr. Zero": {
    skillGrade: "SR",
    type: "Common",
    name: "Mr. Zero",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Palmball: {
    skillGrade: "SR",
    type: "Pitch Type V",
    name: "Palmball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Power Pitch": {
    skillGrade: "SR",
    type: "Pitching Style",
    name: "Power Pitch",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Recover: {
    skillGrade: "SR",
    type: "Common",
    name: "Recover",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "SF Ball": {
    skillGrade: "SR",
    type: "Pitch Type IV",
    name: "SF Ball",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Sinker: {
    skillGrade: "SR",
    type: "Pitch Type VI",
    name: "Sinker",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Slider: {
    skillGrade: "SR",
    type: "Pitch Type II",
    name: "Slider",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Slow Curve": {
    skillGrade: "SR",
    type: "Pitch Type III",
    name: "Slow Curve",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Snake: {
    skillGrade: "SR",
    type: "Pitching Style",
    name: "Snake",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Steel Arm": {
    skillGrade: "SR",
    type: "Common",
    name: "Steel Arm",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Two-Seam": {
    skillGrade: "SR",
    type: "Pitch Type VI",
    name: "Two-Seam",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Anti Walk": {
    skillGrade: "R",
    type: "Common",
    name: "Anti Walk",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Changing Tides": {
    skillGrade: "R",
    type: "Common",
    name: "Changing Tides",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Concentration: {
    skillGrade: "R",
    type: "Common",
    name: "Concentration",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Fire Baller": {
    skillGrade: "R",
    type: "Common",
    name: "Fire Baller",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Fortune: {
    skillGrade: "R",
    type: "Common",
    name: "Fortune",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "No Runs For You": {
    skillGrade: "R",
    type: "Common",
    name: "No Runs For You",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Pin Point": {
    skillGrade: "R",
    type: "Common",
    name: "Pin Point",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Reliever: {
    skillGrade: "R",
    type: "Common",
    name: "Reliever",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Shutter Man": {
    skillGrade: "R",
    type: "Common",
    name: "Shutter Man",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Sidearm: {
    skillGrade: "R",
    type: "Pitching Style",
    name: "Sidearm",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Strikeout King": {
    skillGrade: "R",
    type: "Common",
    name: "Strikeout King",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Underhand: {
    skillGrade: "R",
    type: "Pitching Style",
    name: "Underhand",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Alert: {
    skillGrade: "N",
    type: "Common",
    name: "Alert",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Change of Mood": {
    skillGrade: "N",
    type: "Common",
    name: "Change of Mood",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Confidence: {
    skillGrade: "N",
    type: "Common",
    name: "Confidence",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  Guardian: {
    skillGrade: "N",
    type: "Common",
    name: "Guardian",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Rise of a Hero": {
    skillGrade: "N",
    type: "Common",
    name: "Rise of a Hero",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
  "Special Force": {
    skillGrade: "N",
    type: "Common",
    name: "Special Force",
    valuesByPosition: { "0": 1, CP: 1, RP: 1, SP: 1 },
  },
};

export default skillDefinitions;
